services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network


  backend:
    build:
      context: ./backend
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
