version: '3'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env # Reference the frontend .env file
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "7000:7000"
    env_file:
      - ./backend/.env # Reference the backend .env file
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mypasswd
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:

